#!/usr/bin/env bash
# Install logos-vpn ON THIS MACHINE and start it, from the published image.
#
# One command takes a bare machine to a running mesh member: it fetches the
# image, generates the config, installs a systemd unit and starts it. There is
# no separate "now run the daemon" step.
#
#   sudo ./install.sh join <NETWORK-KEY> --name laptop
#   sudo ./install.sh init --relay                   # create a new mesh
#
# Everything after init/join goes straight to logos-vpn, so its flags are
# whatever that version supports rather than a copy that drifts.
#
# Needs only docker and /dev/net/tun. No Go toolchain, no repository checkout,
# no liblogosdelivery — everything is in the image.
#
# This is the counterpart to scripts/deploy.sh, which pushes to a remote host
# from a machine that has the repo. Here you are already on the box, which is
# the usual case for "I just got a new machine".
#
# What it touches:
#   /etc/logos-vpn/           config
#   /var/lib/logos-vpn/       device identity and announce sequence number
#   /run/logos-vpn/           control socket
#   /usr/local/bin/logos-vpn  wrapper so `logos-vpn status` works on the host
#   a logos-vpn systemd unit, and a container of the same name
#
# Re-running is safe: an existing config and identity are left alone unless
# --force is given. Losing the identity means a new overlay address and looking
# like a different device to every peer, so it is never destroyed by accident.
set -euo pipefail

IMAGE=${IMAGE:-ghcr.io/vpavlin/logos-vpn:latest}
FORCE=0

usage() {
    cat <<EOF
usage: $0 [--image REF] [--force] (init | join <NETWORK-KEY>) [flags...]

  init                 create a new mesh and print its key
  join KEY             join an existing mesh

Everything after init/join is passed straight to logos-vpn, so its flags are
whatever that version supports:

  --name NAME          device name (default: this machine's hostname)
  --relay              also forward for peers that cannot connect directly
  --advertise IP:PORT  public endpoint, if not on a local interface
  --port N             UDP port

This script's own options:
  --image REF          image to run (default: $IMAGE)
  --force              regenerate the config if one exists

Examples:
  sudo $0 join P27KNQ2... --name laptop
  sudo $0 init --relay
EOF
    exit 1
}

# Only this script's own options are parsed here; the first non-option ends it
# and everything from there is the logos-vpn command line.
#
# Deliberately NOT re-declaring --name/--relay/--advertise: they belong to
# logos-vpn, and duplicating them means this script silently fails to support
# any flag added there later.
while [ $# -gt 0 ]; do
    case "$1" in
        --image) IMAGE=$2; shift 2 ;;
        --force) FORCE=1; shift ;;
        -h|--help) usage ;;
        --) shift; break ;;
        -*) echo "unknown option $1"; usage ;;
        *) break ;;
    esac
done

[ $# -gt 0 ] || usage
case "$1" in
    init|join) ;;
    *) echo "expected 'init' or 'join', got '$1'"; usage ;;
esac
SETUP=("$@")

[ "$(id -u)" -eq 0 ] || { echo "run as root (sudo $0 ...)"; exit 1; }

echo "==> checking this machine"
command -v docker >/dev/null || { echo "docker is not installed"; exit 1; }
[ -e /dev/net/tun ] || { echo "no /dev/net/tun — the kernel needs the tun module"; exit 1; }
command -v systemctl >/dev/null || { echo "no systemd; see docker/compose-node.yml to run it yourself"; exit 1; }
echo "  docker $(docker version --format '{{.Server.Version}}' 2>/dev/null || echo '?'), /dev/net/tun present"

# SELinux relabels bind mounts; without :Z the container cannot read its config
# and reports it as missing rather than as a permission problem.
Z=""
if command -v getenforce >/dev/null && [ "$(getenforce 2>/dev/null)" = "Enforcing" ]; then
    Z=":Z"
    echo "  SELinux enforcing, relabelling mounts"
fi

echo "==> fetching $IMAGE"
docker pull -q "$IMAGE" >/dev/null || {
    echo "could not pull $IMAGE"
    echo "if the package is private, either make it public or run: docker login ghcr.io"
    exit 1
}

mkdir -p /etc/logos-vpn /var/lib/logos-vpn /run/logos-vpn
chmod 700 /etc/logos-vpn /var/lib/logos-vpn

# ---------------------------------------------------------------------------
# Config. Generated by the image itself, so this script never needs to know the
# file format.
# ---------------------------------------------------------------------------

if [ -f /etc/logos-vpn/config.toml ] && [ $FORCE -eq 0 ]; then
    echo "==> config already present, leaving it alone (--force to replace)"
else
    echo "==> generating config (${SETUP[0]})"
    # --hostname so the CLI's own "default: hostname" means THIS machine and not
    # the container's random one. Nothing else needs a name passed.
    #
    # --config/--state are appended, so they win over anything the caller typed:
    # the service unit mounts these paths and nothing else would be read.
    docker run --rm \
        --hostname "$(hostname -s 2>/dev/null || hostname)" \
        -v "/etc/logos-vpn:/etc/logos-vpn$Z" \
        -v "/var/lib/logos-vpn:/var/lib/logos-vpn$Z" \
        "$IMAGE" "${SETUP[@]}" \
        --config /etc/logos-vpn/config.toml \
        --state /var/lib/logos-vpn
    chmod 600 /etc/logos-vpn/config.toml
fi

# ---------------------------------------------------------------------------
# Service. A unit wrapping `docker run` rather than compose: compose is a
# separate install, and on podman hosts podman-compose is the least reliable
# part of the stack.
#
# Host networking is deliberate. A VPN node must bind its UDP port on the real
# address — behind docker's bridge the reflexive address peers observe would be
# the gateway's and the source port would be rewritten, so traversal would be
# fighting a layer of NAT that does not exist in reality.
# ---------------------------------------------------------------------------

echo "==> installing the service"
cat > /etc/systemd/system/logos-vpn.service <<EOF
[Unit]
Description=logos-vpn overlay mesh
Documentation=https://github.com/vpavlin/logos-vpn
After=docker.service network-online.target
Wants=network-online.target

[Service]
ExecStartPre=-/usr/bin/docker rm -f logos-vpn
ExecStart=/usr/bin/docker run --rm --name logos-vpn \\
    --network host \\
    --cap-add NET_ADMIN \\
    --device /dev/net/tun \\
    -v /etc/logos-vpn:/etc/logos-vpn$Z \\
    -v /var/lib/logos-vpn:/var/lib/logos-vpn$Z \\
    -v /run/logos-vpn:/run/logos-vpn \\
    $IMAGE daemon --socket /run/logos-vpn/logos-vpn.sock
ExecStop=/usr/bin/docker stop logos-vpn
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

# So `logos-vpn status` works on the host without anyone remembering the
# docker incantation.
#
# No --socket appended: the daemon listens on the CLI's own default, and
# appending it would break every subcommand that does not take the flag —
# `logos-vpn key show` among them.
cat > /usr/local/bin/logos-vpn <<'EOF'
#!/bin/sh
# Thin wrapper: run the CLI inside the running node container.
if ! docker inspect -f '{{.State.Running}}' logos-vpn 2>/dev/null | grep -q true; then
    echo "the logos-vpn container is not running" >&2
    echo "  sudo systemctl status logos-vpn" >&2
    exit 1
fi
exec docker exec logos-vpn logos-vpn "$@"
EOF
chmod 755 /usr/local/bin/logos-vpn

systemctl daemon-reload
systemctl enable logos-vpn >/dev/null 2>&1
# Not `enable --now ... || enable`: that swallowed a failed start and left the
# script reporting success over a node that never came up.
if ! systemctl restart logos-vpn; then
    echo "the service failed to start:"
    journalctl -u logos-vpn --no-pager -n 20
    exit 1
fi

echo "==> waiting for the node to reach the fleet"
for _ in $(seq 1 12); do
    sleep 5
    logos-vpn status >/dev/null 2>&1 && break
done

echo
if ! logos-vpn status 2>&1 | head -12; then
    echo "not answering yet — it may still be connecting."
    echo "  journalctl -u logos-vpn -f"
fi

cat <<EOF

The daemon is running now, and starts on boot.

  systemctl status logos-vpn      # is it up
  logos-vpn status                # who is on the mesh
  logos-vpn paths                 # why a peer is or is not reachable
  journalctl -u logos-vpn -f      # follow the log

EOF

# Both hints below are derived from what actually happened, not from what was
# typed: the config is the source of truth, and a --relay that failed to take
# effect should not produce advice implying it did.
if [ "${SETUP[0]}" = "init" ]; then
    KEY=$(docker run --rm -v "/etc/logos-vpn:/etc/logos-vpn$Z" "$IMAGE" \
        key show --config /etc/logos-vpn/config.toml)
    cat <<EOF
This machine created the mesh. Add others with:

  sudo bash install.sh join $KEY

Treat that key as a password: anyone holding it is a member of the mesh.
EOF
fi

if docker run --rm --entrypoint /bin/sh -v "/etc/logos-vpn:/etc/logos-vpn$Z" "$IMAGE" \
       -c 'grep -q "^relay *= *\"true\"" /etc/logos-vpn/config.toml' 2>/dev/null; then
    echo "This node relays. Open its UDP port if a firewall is in the way:"
    echo "  ufw allow 51820/udp    # or the equivalent"
fi
