#!/usr/bin/env bash
# Set up a logos-vpn node ON THIS MACHINE, from the published image.
#
#   sudo ./install-node.sh --key <NETWORK-KEY> --name laptop
#   sudo ./install-node.sh --init --name vps --relay      # create a new mesh
#
# Needs only docker and /dev/net/tun. No Go toolchain, no repository checkout,
# no liblogosdelivery — everything is in the image.
#
# This is the counterpart to scripts/deploy.sh, which pushes to a remote host
# from a machine that has the repo. Here you are already on the box, which is
# the usual case for "I just got a new machine".
#
# What it touches:
#   /etc/logos-vpn/           config
#   /var/lib/logos-vpn/       device identity and announce sequence number
#   /run/logos-vpn/           control socket
#   /usr/local/bin/logos-vpn  wrapper so `logos-vpn status` works on the host
#   a logos-vpn systemd unit, and a container of the same name
#
# Re-running is safe: an existing config and identity are left alone unless
# --force is given. Losing the identity means a new overlay address and looking
# like a different device to every peer, so it is never destroyed by accident.
set -euo pipefail

IMAGE=${IMAGE:-ghcr.io/vpavlin/logos-vpn:latest}
KEY=""
NAME=$(hostname -s 2>/dev/null || hostname)
INIT=0
RELAY=0
FORCE=0
ADVERTISE=""

usage() {
    cat <<EOF
usage: $0 (--key <NETWORK-KEY> | --init) [options]

  --key KEY          join an existing mesh
  --init             create a new mesh and print its key
  --name NAME        this device's name in the mesh (default: $NAME)
  --relay            also forward traffic for peers that cannot connect directly
  --advertise IP:PORT  publicly reachable address, if not auto-detected
  --force            replace an existing config (keeps the device identity)
  --image REF        image to run (default: $IMAGE)
EOF
    exit 1
}

while [ $# -gt 0 ]; do
    case "$1" in
        --key)       KEY=$2; shift 2 ;;
        --init)      INIT=1; shift ;;
        --name)      NAME=$2; shift 2 ;;
        --relay)     RELAY=1; shift ;;
        --advertise) ADVERTISE=$2; shift 2 ;;
        --force)     FORCE=1; shift ;;
        --image)     IMAGE=$2; shift 2 ;;
        -h|--help)   usage ;;
        *) echo "unknown option $1"; usage ;;
    esac
done

[ -n "$KEY" ] || [ $INIT -eq 1 ] || { echo "need --key or --init"; usage; }
[ "$(id -u)" -eq 0 ] || { echo "run as root (sudo $0 ...)"; exit 1; }

echo "==> checking this machine"
command -v docker >/dev/null || { echo "docker is not installed"; exit 1; }
[ -e /dev/net/tun ] || { echo "no /dev/net/tun — the kernel needs the tun module"; exit 1; }
command -v systemctl >/dev/null || { echo "no systemd; see docker/compose-node.yml to run it yourself"; exit 1; }
echo "  docker $(docker version --format '{{.Server.Version}}' 2>/dev/null || echo '?'), /dev/net/tun present"

# SELinux relabels bind mounts; without :Z the container cannot read its config
# and reports it as missing rather than as a permission problem.
Z=""
if command -v getenforce >/dev/null && [ "$(getenforce 2>/dev/null)" = "Enforcing" ]; then
    Z=":Z"
    echo "  SELinux enforcing, relabelling mounts"
fi

echo "==> fetching $IMAGE"
docker pull -q "$IMAGE" >/dev/null || {
    echo "could not pull $IMAGE"
    echo "if the package is private, either make it public or run: docker login ghcr.io"
    exit 1
}

mkdir -p /etc/logos-vpn /var/lib/logos-vpn /run/logos-vpn
chmod 700 /etc/logos-vpn /var/lib/logos-vpn

# ---------------------------------------------------------------------------
# Config. Generated by the image itself, so this script never needs to know the
# file format.
# ---------------------------------------------------------------------------

if [ -f /etc/logos-vpn/config.toml ] && [ $FORCE -eq 0 ]; then
    echo "==> config already present, leaving it alone (--force to replace)"
else
    echo "==> generating config"
    ARGS=(--config /etc/logos-vpn/config.toml --state /var/lib/logos-vpn --name "$NAME")
    [ -n "$ADVERTISE" ] && ARGS+=(--advertise "$ADVERTISE")
    [ $RELAY -eq 1 ] && ARGS+=(--relay)

    RUN=(docker run --rm
        -v "/etc/logos-vpn:/etc/logos-vpn$Z"
        -v "/var/lib/logos-vpn:/var/lib/logos-vpn$Z"
        "$IMAGE")

    if [ $INIT -eq 1 ]; then
        "${RUN[@]}" init "${ARGS[@]}"
    else
        "${RUN[@]}" join "$KEY" "${ARGS[@]}"
    fi
    chmod 600 /etc/logos-vpn/config.toml
fi

# ---------------------------------------------------------------------------
# Service. A unit wrapping `docker run` rather than compose: compose is a
# separate install, and on podman hosts podman-compose is the least reliable
# part of the stack.
#
# Host networking is deliberate. A VPN node must bind its UDP port on the real
# address — behind docker's bridge the reflexive address peers observe would be
# the gateway's and the source port would be rewritten, so traversal would be
# fighting a layer of NAT that does not exist in reality.
# ---------------------------------------------------------------------------

echo "==> installing the service"
cat > /etc/systemd/system/logos-vpn.service <<EOF
[Unit]
Description=logos-vpn overlay mesh
Documentation=https://github.com/vpavlin/logos-vpn
After=docker.service network-online.target
Wants=network-online.target

[Service]
ExecStartPre=-/usr/bin/docker rm -f logos-vpn
ExecStart=/usr/bin/docker run --rm --name logos-vpn \\
    --network host \\
    --cap-add NET_ADMIN \\
    --device /dev/net/tun \\
    -v /etc/logos-vpn:/etc/logos-vpn$Z \\
    -v /var/lib/logos-vpn:/var/lib/logos-vpn$Z \\
    -v /run/logos-vpn:/run/logos-vpn \\
    $IMAGE daemon --socket /run/logos-vpn/logos-vpn.sock
ExecStop=/usr/bin/docker stop logos-vpn
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

# So `logos-vpn status` works on the host without anyone remembering the
# docker incantation.
cat > /usr/local/bin/logos-vpn <<'EOF'
#!/bin/sh
# Thin wrapper: run the CLI inside the running node container.
exec docker exec logos-vpn logos-vpn "$@" --socket /run/logos-vpn/logos-vpn.sock
EOF
chmod 755 /usr/local/bin/logos-vpn

systemctl daemon-reload
systemctl enable --now logos-vpn >/dev/null 2>&1 || systemctl enable logos-vpn

echo "==> waiting for the node to reach the fleet"
for _ in $(seq 1 12); do
    sleep 5
    logos-vpn status >/dev/null 2>&1 && break
done

echo
logos-vpn status 2>&1 | head -12 || {
    echo "not answering yet; check: journalctl -u logos-vpn -f"
}

cat <<EOF

Useful here:
  logos-vpn status
  logos-vpn paths
  journalctl -u logos-vpn -f

EOF

if [ $INIT -eq 1 ]; then
    cat <<EOF
This machine created the mesh. Join others with its key:

  sudo ./install-node.sh --key $(docker run --rm -v "/etc/logos-vpn:/etc/logos-vpn$Z" "$IMAGE" key show --config /etc/logos-vpn/config.toml) --name <their-name>

Treat that key as a password: anyone holding it is a member of the mesh.
EOF
fi

if [ $RELAY -eq 1 ]; then
    echo "This node relays. Open its UDP port if a firewall is in the way:"
    echo "  ufw allow 51820/udp    # or the equivalent"
fi
